name: 'Deploy Azure Resource'

inputs:
  az_rg_n:
    description: “Azure ResourceGroup name”
    required: true
  vm_username:
    description: "test vm username"
    required: true
  vm_password:
    description: "test vm password"
    required: true

runs:
  using: 'composite'
  steps:
  - name: test-bicep-file-deployment
    uses: azure/arm-deploy@v1
    with:
      scope: resourcegroup
      resourceGroupName: ${{ inputs.az_rg_n }}
      deploymentMode: Complete
      template: examples/examples.bicep
      parameters: vm_username=${{ inputs.vm_username }} vm_password=${{ inputs.vm_password }}
      failOnStdErr: true